#!/bin/sh

PASSPHRASE="$(op read "$OP_PIN_ITEM")"

echo "OK"
while read cmd rest; do
  echo "cmd=$cmd rest=$rest" >&2
  case "$cmd" in
    \#*)
      echo "OK"
      ;;
    GETPIN)
      echo "D ${PASSPHRASE}"
      echo "OK"
      ;;
    BYE)
      echo "OK"
      exit 0
      ;;
    *)
      echo "OK"
      ;;
  esac
done
